# Homework 8:

For questions 1-4 use the orthologs.sqlite database we created in class (include the database in the directory with the homework when returning it to github).

In [1]:
import sqlite3 as sql
import pandas as pd
# First connect to database
con = sql.connect("orthologs.sqlite")

In [2]:
%load_ext sql
%reload_ext sql
%sql sqlite:///test.sqlite

u'Connected: None@test.sqlite'

In [3]:
pd.read_sql("SELECT * FROM sqlite_master;", con)

,type,name,tbl_name,rootpage,sql
0,table,sequences,sequences,61,"CREATE TABLE ""sequences"" (\n""gene_name"" TEXT,\..."
1,table,gff,gff,11113,"CREATE TABLE ""gff"" (\n""acc"" TEXT,\n ""chrom"" T..."
2,table,cai,cai,2,"CREATE TABLE ""cai"" (\n""title"" TEXT,\n ""CAI"" R..."
3,table,orthologs,orthologs,37,"CREATE TABLE ""orthologs"" (\n""cerevisiae"" TEXT,..."

In [4]:
pd.read_sql("SELECT * FROM orthologs limit 2", con) #to view the contents of each table

  cerevisiae  mikatae  paradoxus  bayanus
0    YAL001C      305        176      349
1    YAL002W      301        186      346

In [5]:
pd.read_sql("SELECT * FROM sequences limit 2", con)

  gene_name    species                                                seq
0     24882  paradoxus  TGACTGAAACTCCTGTGAAACCTTAGAAAGAATACCGCTATGAAAT...
1     25548  paradoxus  GGCAACTTGGCCGAGTGGTTAAGGCGAAAGATTAGAAATCTTTTGG...

In [6]:
pd.read_sql("SELECT * FROM cai limit 2", con)

     title    CAI
0  YAL001C  0.121
1  YAL002W  0.134

In [7]:
pd.read_sql("SELECT * FROM gff limit 2", con)

       acc chrom  start     end strand     feature                 description
0     chrI  chrI      1  230218      .  chromosome             full chromosome
1  YAL069W  chrI    335     649      +        gene  Dubious open reading frame

__Exercise 1.__ Create a query that will return the gene name, cai value and sequence for all yeast genes with CAI values larger than 0.85.

In [31]:
pd.read_sql("SELECT title, CAI, seq FROM cai, sequences WHERE gene_name = title and CAI > .85", con) #gene name in one equals the gene name in the other

      title    CAI                                                seq
0   YAL038W  0.893  ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...
1   YBR118W  0.876  ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...
2   YGL030W  0.865  ATGGCCCCAGTTAAATCCCAAGAATCTATCAACCAAAAGTTGGCTT...
3   YGR192C  0.924  ATGGTTAGAGTTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
4   YGR254W  0.871  ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
5   YHR174W  0.892  ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
6   YJL052W  0.856  ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
7   YJL189W  0.915  ATGGCTGCTCAAAAGTCTTTCAGAATCAAGCAAAAAATGGCTAAGG...
8   YJR009C  0.905  ATGGTTAGAGTTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
9   YKL060C  0.869  ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...
10  YLR044C  0.904  ATGTCTGAAATTACTTTGGGTAAATATTTGTTCGAAAGATTAAAGC...
11  YLR061W  0.859  ATGGCCCCAAACACTTCCAGAAAGCAAAAGATTGCCAAGACCTTTA...
12  YLR110C  0.870  ATGCAATTTTCTACTGTCGCTTCTATCGCCGCTGTCGCCGCTGTCG...
13  YPR043W  0.872  ATGGCTAAAAGAACTAAGAAGGTTGGTATCACTGGTAAGTACGGTG...
14  YPR080W  0.871  ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...

__Exercise 2.__ Modify the query above to return the gene name in yeast, the gene names in the other three species, the cai value and the sequence for all yeast genes with a cai value larger that 0.8 and that have orthologs in the other three species.

In [32]:
pd.read_sql("SELECT orthologs.*, cai, seq FROM cai, orthologs, sequences WHERE gene_name = cerevisiae and cerevisiae = title and CAI > .8", con)

,cerevisiae,mikatae,paradoxus,bayanus,CAI,seq
0,YAL038W,133,366,146,0.893,ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...
1,YBR181C,575,1733,1653,0.846,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...
2,YCR012W,2014,2464,2653,0.815,ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGG...
3,YCR031C,1948,2539,2721,0.805,ATGTCTAACGTTGTTCAAGCTCGTGACAATTCCCAAGTTTTTGGTG...
4,YEL034W,5747,5869,6110,0.814,ATGTCTGACGAAGAACATACCTTTGAAACTGCTGACGCTGGTTCCT...
5,YGL123W,8023,8791,8164,0.801,ATGTCTGCTCCAGAAGCTCAACAACAAAAGAGAGGTGGTTTCGGTG...
6,YGL135W,8073,8842,8219,0.832,ATGTCTAAGATCACCTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
7,YGR254W,9167,9320,9559,0.871,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
8,YHL015W,9576,10453,23293,0.827,ATGTCTGACTTTCAAAAGGAAAAGGTTGAAGAACAAGAACAACAAC...
9,YHL033C,9483,10537,10119,0.842,ATGGCCCCAGGTAAGAAAGTCGCTCCAGCTCCATTCGGTGCTAAGT...
10,YHR174W,10272,9737,10953,0.892,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
11,YJL052W,12006,11467,7692,0.856,ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
12,YJL190C,11505,12007,12309,0.812,ATGACCAGATCTTCCGTTTTAGCTGATGCTTTGAATGCCATTAACA...
13,YJR123W,12651,12748,13807,0.838,ATGTCTGACACCGAAGCTCCAGTTGAAGTTCAAGAAGATTTCGAAG...
14,YKL060C,13447,13709,14543,0.869,ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...
15,YKL152C,13136,14038,14168,0.811,ATGCCAAAGTTAGTTTTAGTTAGACACGGTCAATCCGAATGGAACG...
16,YLR355C,15884,15522,16470,0.802,ATGTTGAGAACTCAAGCCGCCAGATTGATCTGCAACTCCCGTGTCA...
17,YML024W,16317,17429,17865,0.810,ATGGGTAGAGTTAGAACCAAGACCGTCAAGCGTGCTTCTAAGGCTT...
18,YOL039W,19423,20163,22682,0.804,ATGAAGTACTTAGCTGCTTACCTATTATTGAACGCTGCTGGTAACA...
19,YOL086C,19645,19978,22315,0.811,ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCC...
20,YOL120C,19772,19865,22100,0.812,ATGGGTATCGATCACACTTCCAAGCAACACAAGAGATCTGGTCACA...
21,YOR063W,19967,20560,22996,0.830,ATGTCTCACAGAAAGTACGAAGCACCACGTCACGGTCATTTAGGTT...
22,YOR369C,20601,21712,24125,0.844,ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTG...
23,YPL090C,21951,22560,25232,0.837,ATGAAGTTGAACATTTCTTACCCAGTTAACGGGTCTCAAAAGACCT...
24,YPL131W,21794,22413,25389,0.830,ATGGCTTTCCAAAAAGACGCTAAGTCCTCTGCTTACTCCTCTCGTT...
25,YPL220W,21446,22041,24818,0.821,ATGTCCAAGATCACTTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
26,YPR080W,22559,23137,25835,0.871,ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...

__Exercise 3.__ Perform the same query as above, but this time include the chromosome number of the gene in the output.

In [33]:
pd.read_sql("SELECT orthologs.*, cai, chrom, seq FROM cai, orthologs, gff, sequences WHERE gene_name = cerevisiae and cerevisiae = title and cerevisiae = acc and CAI > .8", con)

,cerevisiae,mikatae,paradoxus,bayanus,CAI,chrom,seq
0,YAL038W,133,366,146,0.893,chrI,ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...
1,YBR181C,575,1733,1653,0.846,chrII,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...
2,YCR012W,2014,2464,2653,0.815,chrIII,ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGG...
3,YCR031C,1948,2539,2721,0.805,chrIII,ATGTCTAACGTTGTTCAAGCTCGTGACAATTCCCAAGTTTTTGGTG...
4,YEL034W,5747,5869,6110,0.814,chrV,ATGTCTGACGAAGAACATACCTTTGAAACTGCTGACGCTGGTTCCT...
5,YGL123W,8023,8791,8164,0.801,chrVII,ATGTCTGCTCCAGAAGCTCAACAACAAAAGAGAGGTGGTTTCGGTG...
6,YGL135W,8073,8842,8219,0.832,chrVII,ATGTCTAAGATCACCTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
7,YGR254W,9167,9320,9559,0.871,chrVII,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
8,YHL015W,9576,10453,23293,0.827,chrVIII,ATGTCTGACTTTCAAAAGGAAAAGGTTGAAGAACAAGAACAACAAC...
9,YHL033C,9483,10537,10119,0.842,chrVIII,ATGGCCCCAGGTAAGAAAGTCGCTCCAGCTCCATTCGGTGCTAAGT...
10,YHR174W,10272,9737,10953,0.892,chrVIII,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...
11,YJL052W,12006,11467,7692,0.856,chrX,ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...
12,YJL190C,11505,12007,12309,0.812,chrX,ATGACCAGATCTTCCGTTTTAGCTGATGCTTTGAATGCCATTAACA...
13,YJR123W,12651,12748,13807,0.838,chrX,ATGTCTGACACCGAAGCTCCAGTTGAAGTTCAAGAAGATTTCGAAG...
14,YKL060C,13447,13709,14543,0.869,chrXI,ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...
15,YKL152C,13136,14038,14168,0.811,chrXI,ATGCCAAAGTTAGTTTTAGTTAGACACGGTCAATCCGAATGGAACG...
16,YLR355C,15884,15522,16470,0.802,chrXII,ATGTTGAGAACTCAAGCCGCCAGATTGATCTGCAACTCCCGTGTCA...
17,YML024W,16317,17429,17865,0.810,chrXIII,ATGGGTAGAGTTAGAACCAAGACCGTCAAGCGTGCTTCTAAGGCTT...
18,YOL039W,19423,20163,22682,0.804,chrXV,ATGAAGTACTTAGCTGCTTACCTATTATTGAACGCTGCTGGTAACA...
19,YOL086C,19645,19978,22315,0.811,chrXV,ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCC...
20,YOL120C,19772,19865,22100,0.812,chrXV,ATGGGTATCGATCACACTTCCAAGCAACACAAGAGATCTGGTCACA...
21,YOR063W,19967,20560,22996,0.830,chrXV,ATGTCTCACAGAAAGTACGAAGCACCACGTCACGGTCATTTAGGTT...
22,YOR369C,20601,21712,24125,0.844,chrXV,ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTG...
23,YPL090C,21951,22560,25232,0.837,chrXVI,ATGAAGTTGAACATTTCTTACCCAGTTAACGGGTCTCAAAAGACCT...
24,YPL131W,21794,22413,25389,0.830,chrXVI,ATGGCTTTCCAAAAAGACGCTAAGTCCTCTGCTTACTCCTCTCGTT...
25,YPL220W,21446,22041,24818,0.821,chrXVI,ATGTCCAAGATCACTTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...
26,YPR080W,22559,23137,25835,0.871,chrXVI,ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...

__Exercise 4.__ Now generate a table with the number of genes per chromosome that have CAI larger than 0.5 and have orthologs in the other three yeast species.

In [35]:
pd.read_sql("SELECT chrom, count(chrom)  FROM gff, cai WHERE title = acc and CAI > .5 GROUP BY chrom", con)

      chrom  count(chrom)
0      chrI             4
1     chrII            24
2    chrIII             4
3     chrIV            34
4     chrIX             9
5      chrV            14
6     chrVI             7
7    chrVII            25
8   chrVIII            13
9      chrX            18
10    chrXI            13
11   chrXII            34
12  chrXIII            15
13   chrXIV            14
14    chrXV            20
15   chrXVI            17

__Exercise 5:__ Download the yeast genome gff file from this link: http://downloads.yeastgenome.org/curation/chromosomal_feature/saccharomyces_cerevisiae.gff

Read about the gff format and write a script that will create a database table with all the yeast genes. Your table should have the following columns: `Accession number, Chromosome number, Start Position, End Position, Strand, Feature, Description`.

All this information should be available form the gff file. Only include in your database the yeast protein coding genes, the tRNA coding genes and the full chromosomes. Your final table should have one row per gene/chromosome for a total of 6916 rows.

Note that the description of several genes, and even some gene names contain special HTML characters, like %20. To convert these to text you should use the `unquote()` function of the `urllib` package. Do that before trying to use your regular expressions.

In [29]:
#start from new file and make gff
filein = open('saccharomyces_cerevisiae.gff')
g = []

import urllib
import re

for line in filein:
    line = urllib.unquote(line)
    if line[0:3] == '###':
        break
    elif line[0] == '#':
        continue
    else:
        temp = line.split() #split returs a string with 9 elements
        if temp[2] in ['gene', 'tRNA_gene', 'chromosome']:
            m = re.search('ID=([-\w\(\)]+);',temp[8])
            acc = m.group(1)
            
            
            g.append([acc, temp[0],temp[3], temp[4], temp[6], temp[2], temp[8]])
pd.DataFrame(g,columns=['Acc','Chrom','Start','End','Strand','Feature','Description'])

,Acc,Chrom,Start,End,Strand,Feature,Description
0,chrI,chrI,1,230218,.,chromosome,ID=chrI;dbxref=NCBI:;Name=chrI
1,YAL069W,chrI,335,649,+,gene,ID=YAL069W;Name=YAL069W;Ontology_term=GO:00036...
2,YAL068W-A,chrI,538,792,+,gene,ID=YAL068W-A;Name=YAL068W-A;Ontology_term=GO:0...
3,YAL068C,chrI,1807,2169,-,gene,"ID=YAL068C;Name=YAL068C;gene=PAU8;Alias=PAU8,s..."
4,YAL067W-A,chrI,2480,2707,+,gene,ID=YAL067W-A;Name=YAL067W-A;Ontology_term=GO:0...
5,YAL067C,chrI,7235,9016,-,gene,"ID=YAL067C;Name=YAL067C;gene=SEO1;Alias=SEO1,p..."
6,YAL066W,chrI,10091,10399,+,gene,ID=YAL066W;Name=YAL066W;Ontology_term=GO:00036...
7,YAL065C,chrI,11565,11951,-,gene,ID=YAL065C;Name=YAL065C;Ontology_term=GO:00036...
8,YAL064W-B,chrI,12046,12426,+,gene,ID=YAL064W-B;Name=YAL064W-B;Ontology_term=GO:0...
9,YAL064C-A,chrI,13363,13743,-,gene,ID=YAL064C-A;Name=YAL064C-A;gene=TDA8;Alias=TD...
10,YAL064W,chrI,21566,21850,+,gene,ID=YAL064W;Name=YAL064W;Ontology_term=GO:00036...
11,YAL063C-A,chrI,22395,22685,-,gene,ID=YAL063C-A;Name=YAL063C-A;Ontology_term=GO:0...
12,YAL063C,chrI,24000,27968,-,gene,"ID=YAL063C;Name=YAL063C;gene=FLO9;Alias=FLO9,f..."
13,YAL062W,chrI,31567,32940,+,gene,"ID=YAL062W;Name=YAL062W;gene=GDH3;Alias=GDH3,F..."
14,YAL061W,chrI,33448,34701,+,gene,"ID=YAL061W;Name=YAL061W;gene=BDH2;Alias=BDH2,p..."
15,YAL060W,chrI,35155,36303,+,gene,"ID=YAL060W;Name=YAL060W;gene=BDH1;Alias=BDH1,(..."
16,YAL059C-A,chrI,36496,36918,-,gene,ID=YAL059C-A;Name=YAL059C-A;Ontology_term=GO:0...
17,YAL059W,chrI,36509,37147,+,gene,ID=YAL059W;Name=YAL059W;gene=ECM1;Alias=ECM1;O...
18,YAL058W,chrI,37464,38972,+,gene,"ID=YAL058W;Name=YAL058W;gene=CNE1;Alias=CNE1,F..."
19,YAL056C-A,chrI,38696,39046,-,gene,ID=YAL056C-A;Name=YAL056C-A;Alias=YAL058C-A;On...
20,YAL056W,chrI,39259,41901,+,gene,"ID=YAL056W;Name=YAL056W;gene=GPB2;Alias=GPB2,K..."
21,YAL055W,chrI,42177,42719,+,gene,ID=YAL055W;Name=YAL055W;gene=PEX22;Alias=PEX22...
22,YAL054C,chrI,42881,45022,-,gene,"ID=YAL054C;Name=YAL054C;gene=ACS1;Alias=ACS1,F..."
23,YAL053W,chrI,45899,48250,+,gene,"ID=YAL053W;Name=YAL053W;gene=FLC2;Alias=FLC2,H..."
24,YAL051W,chrI,48564,51707,+,gene,"ID=YAL051W;Name=YAL051W;gene=OAF1;Alias=OAF1,Y..."
25,YAL049C,chrI,51855,52595,-,gene,"ID=YAL049C;Name=YAL049C;gene=AIM2;Alias=AIM2,p..."
26,YAL048C,chrI,52801,54789,-,gene,"ID=YAL048C;Name=YAL048C;gene=GEM1;Alias=GEM1,E..."
27,YAL047W-A,chrI,54584,54913,+,gene,ID=YAL047W-A;Name=YAL047W-A;Ontology_term=GO:0...
28,YAL047C,chrI,54989,56857,-,gene,ID=YAL047C;Name=YAL047C;gene=SPC72;Alias=SPC72...
29,YAL046C,chrI,57029,57385,-,gene,"ID=YAL046C;Name=YAL046C;gene=BOL3;Alias=BOL3,A..."
...,...,...,...,...,...,...,...
6886,Q0140,chrmt,48901,50097,+,gene,"ID=Q0140;Name=Q0140;gene=VAR1;Alias=VAR1,VARI,..."
6887,Q0142,chrmt,51052,51228,+,gene,ID=Q0142;Name=Q0142;Alias=ORF9;Ontology_term=G...
6888,Q0143,chrmt,51277,51429,+,gene,ID=Q0143;Name=Q0143;Alias=ORF10;Ontology_term=...
6889,Q0144,chrmt,54109,54438,+,gene,"ID=Q0144;Name=Q0144;Ontology_term=GO:0003674,G..."
6890,Q0160,chrmt,61022,61729,+,gene,"ID=Q0160;Name=Q0160;gene=SCEI;Alias=SCEI,I-Sce..."
6891,tT(UGU)Q1,chrmt,63862,63937,+,tRNA_gene,ID=tT(UGU)Q1;Name=tT(UGU)Q1;Ontology_term=GO:0...
6892,tC(GCA)Q,chrmt,64415,64490,+,tRNA_gene,ID=tC(GCA)Q;Name=tC(GCA)Q;Ontology_term=GO:000...
6893,tH(GUG)Q,chrmt,64596,64670,+,tRNA_gene,ID=tH(GUG)Q;Name=tH(GUG)Q;Ontology_term=GO:000...
6894,Q0182,chrmt,65770,66174,+,gene,ID=Q0182;Name=Q0182;Alias=ORF11;Ontology_term=...
6895,tL(UAA)Q,chrmt,66095,66179,+,tRNA_gene,ID=tL(UAA)Q;Name=tL(UAA)Q;Ontology_term=GO:000...
6896,tQ(UUG)Q,chrmt,66210,66285,+,tRNA_gene,ID=tQ(UUG)Q;Name=tQ(UUG)Q;Ontology_term=GO:000...
6897,tK(UUU)Q,chrmt,67061,67134,+,tRNA_gene,ID=tK(UUU)Q;Name=tK(UUU)Q;Ontology_term=GO:000...
6898,tR(UCU)Q1,chrmt,67309,67381,+,tRNA_gene,ID=tR(UCU)Q1;Name=tR(UCU)Q1;Ontology_term=GO:0...
6899,tG(UCC)Q,chrmt,67468,67542,+,tRNA_gene,ID=tG(UCC)Q;Name=tG(UCC)Q;Ontology_term=GO:000...
6900,tD(GUC)Q,chrmt,68322,68396,+,tRNA_gene,ID=tD(GUC)Q;Name=tD(GUC)Q;Ontology_term=GO:000...
6901,tS(GCU)Q1,chrmt,69203,69288,+,tRNA_gene,ID=tS(GCU)Q1;Name=tS(GCU)Q1;Ontology_term=GO:0...
6902,tR(ACG)Q2,chrmt,69289,69362,+,tRNA_gene,ID=tR(ACG)Q2;Name=tR(ACG)Q2;Ontology_term=GO:0...
6903,tA(UGC)Q,chrmt,69846,69921,+,tRNA_gene,ID=tA(UGC)Q;Name=tA(UGC)Q;Ontology_term=GO:000...
6904,tI(GAU)Q,chrmt,70162,70237,+,tRNA_gene,ID=tI(GAU)Q;Name=tI(GAU)Q;Ontology_term=GO:000...
6905,tY(GUA)Q,chrmt,70824,70907,+,tRNA_gene,ID=tY(GUA)Q;Name=tY(GUA)Q;Ontology_term=GO:000...
6906,tN(GUU)Q,chrmt,71433,71503,+,tRNA_gene,ID=tN(GUU)Q;Name=tN(GUU)Q;Ontology_term=GO:000...
6907,tM(CAU)Q1,chrmt,72630,72705,+,tRNA_gene,ID=tM(CAU)Q1;Name=tM(CAU)Q1;Ontology_term=GO:0...
6908,Q0250,chrmt,73758,74513,+,gene,"ID=Q0250;Name=Q0250;gene=COX2;Alias=COX2,OXI1,..."
6909,Q0255,chrmt,74495,75984,+,gene,"ID=Q0255;Name=Q0255;Alias=ORF1,RF1,maturase-like"
6910,tF(GAA)Q,chrmt,77431,77505,+,tRNA_gene,ID=tF(GAA)Q;Name=tF(GAA)Q;Ontology_term=GO:000...
6911,tT(UAG)Q2,chrmt,78089,78162,-,tRNA_gene,ID=tT(UAG)Q2;Name=tT(UAG)Q2;Alias=tT(XXX)Q2;On...
6912,tV(UAC)Q,chrmt,78533,78608,+,tRNA_gene,ID=tV(UAC)Q;Name=tV(UAC)Q;Ontology_term=GO:000...
6913,Q0275,chrmt,79213,80022,+,gene,"ID=Q0275;Name=Q0275;gene=COX3;Alias=COX3,OXI2,..."
6914,tM(CAU)Q2,chrmt,85035,85112,+,tRNA_gene,ID=tM(CAU)Q2;Name=tM(CAU)Q2;Ontology_term=GO:0...
6915,Q0297,chrmt,85554,85709,+,gene,ID=Q0297;Name=Q0297;Alias=ORF12;Ontology_term=...

In [30]:
pd.read_sql('Select * FROM gff', con)

,acc,chrom,start,end,strand,feature,description
0,chrI,chrI,1,230218,.,chromosome,full chromosome
1,YAL069W,chrI,335,649,+,gene,Dubious open reading frame
2,YAL068W-A,chrI,538,792,+,gene,Dubious open reading frame
3,YAL068C,chrI,1807,2169,-,gene,Protein of unknown function
4,YAL067W-A,chrI,2480,2707,+,gene,Putative protein of unknown function
5,YAL067C,chrI,7235,9016,-,gene,Putative permease
6,YAL066W,chrI,10091,10399,+,gene,Dubious open reading frame
7,YAL065C,chrI,11565,11951,-,gene,Putative protein of unknown function
8,YAL064W-B,chrI,12046,12426,+,gene,Fungal-specific protein of unknown function
9,YAL064C-A,chrI,13363,13743,-,gene,Putative protein of unknown function
10,YAL064W,chrI,21566,21850,+,gene,Protein of unknown function
11,YAL063C-A,chrI,22395,22685,-,gene,Putative protein of unknown function
12,YAL063C,chrI,24000,27968,-,gene,Lectin-like protein with similarity to Flo1p
13,YAL062W,chrI,31567,32940,+,gene,NADP(+)-dependent glutamate dehydrogenase
14,YAL061W,chrI,33448,34701,+,gene,Putative medium-chain alcohol dehydrogenase wi...
15,YAL060W,chrI,35155,36303,+,gene,"NAD-dependent (R,R)-butanediol dehydrogenase"
16,YAL059C-A,chrI,36496,36918,-,gene,Dubious open reading frame
17,YAL059W,chrI,36509,37147,+,gene,Pre-ribosomal factor involved in 60S ribosomal...
18,YAL058W,chrI,37464,38972,+,gene,Calnexin
19,YAL056C-A,chrI,38696,39046,-,gene,Dubious open reading frame
20,YAL056W,chrI,39259,41901,+,gene,Multistep regulator of cAMP-PKA signaling
21,YAL055W,chrI,42177,42719,+,gene,Putative peroxisomal membrane protein
22,YAL054C,chrI,42881,45022,-,gene,Acetyl-coA synthetase isoform
23,YAL053W,chrI,45899,48250,+,gene,Putative calcium channel involved in calcium r...
24,YAL051W,chrI,48564,51707,+,gene,Oleate-activated transcription factor
25,YAL049C,chrI,51855,52595,-,gene,Cytoplasmic protein involved in mitochondrial ...
26,YAL048C,chrI,52801,54789,-,gene,"Outer mitochondrial membrane GTPase, subunit o..."
27,YAL047W-A,chrI,54584,54913,+,gene,Dubious open reading frame
28,YAL047C,chrI,54989,56857,-,gene,Gamma-tubulin small complex (gamma-TuSC) receptor
29,YAL046C,chrI,57029,57385,-,gene,Protein involved in Fe-S cluster transfer to m...
...,...,...,...,...,...,...,...
6886,Q0140,chrmt,48901,50097,+,gene,Mitochondrial ribosomal protein of the small s...
6887,Q0142,chrmt,51052,51228,+,gene,Dubious open reading frame
6888,Q0143,chrmt,51277,51429,+,gene,Dubious open reading frame
6889,Q0144,chrmt,54109,54438,+,gene,Dubious open reading frame
6890,Q0160,chrmt,61022,61729,+,gene,I-SceI DNA endonuclease
6891,tT(UGU)Q1,chrmt,63862,63937,+,tRNA_gene,Mitochondrial threonine tRNA (tRNA-Thr)
6892,tC(GCA)Q,chrmt,64415,64490,+,tRNA_gene,Mitochondrial cysteine tRNA (tRNA-Cys)
6893,tH(GUG)Q,chrmt,64596,64670,+,tRNA_gene,Mitochondrial histidine tRNA (tRNA-His)
6894,Q0182,chrmt,65770,66174,+,gene,Dubious open reading frame
6895,tL(UAA)Q,chrmt,66095,66179,+,tRNA_gene,Mitochondrial leucine tRNA (tRNA-Leu)
6896,tQ(UUG)Q,chrmt,66210,66285,+,tRNA_gene,Mitochondrial glutamine tRNA (tRNA-Gln)
6897,tK(UUU)Q,chrmt,67061,67134,+,tRNA_gene,Mitochondrial lysine tRNA (tRNA-Lys)
6898,tR(UCU)Q1,chrmt,67309,67381,+,tRNA_gene,Mitochondrial arginine tRNA (tRNA-Arg)
6899,tG(UCC)Q,chrmt,67468,67542,+,tRNA_gene,Mitochondrial glycine tRNA (tRNA-Gly)
6900,tD(GUC)Q,chrmt,68322,68396,+,tRNA_gene,Mitochondrial aspartate tRNA (tRNA-Asp)
6901,tS(GCU)Q1,chrmt,69203,69288,+,tRNA_gene,Mitochondrial serine tRNA (tRNA-Ser)
6902,tR(ACG)Q2,chrmt,69289,69362,+,tRNA_gene,Mitochondrial arginine tRNA (tRNA-Arg)
6903,tA(UGC)Q,chrmt,69846,69921,+,tRNA_gene,Mitochondrial alanine tRNA (tRNA-Ala)
6904,tI(GAU)Q,chrmt,70162,70237,+,tRNA_gene,Mitochondrial isoleucine tRNA (tRNA-Ile)
6905,tY(GUA)Q,chrmt,70824,70907,+,tRNA_gene,Mitochondrial tyrosine tRNA (tRNA-Tyr)
6906,tN(GUU)Q,chrmt,71433,71503,+,tRNA_gene,Mitochondrial asparagine tRNA (tRNA-Asn)
6907,tM(CAU)Q1,chrmt,72630,72705,+,tRNA_gene,Mitochondrial methionine tRNA (tRNA-Met)
6908,Q0250,chrmt,73758,74513,+,gene,Subunit II of cytochrome c oxidase (Complex IV)
6909,Q0255,chrmt,74495,75984,+,gene,Maturase-like protein
6910,tF(GAA)Q,chrmt,77431,77505,+,tRNA_gene,Mitochondrial phenylalanine tRNA (tRNA-Phe)
6911,tT(UAG)Q2,chrmt,78089,78162,-,tRNA_gene,Mitochondrial threonine tRNA (tRNA-Thr)
6912,tV(UAC)Q,chrmt,78533,78608,+,tRNA_gene,Mitochondrial valine tRNA (tRNA-Val)
6913,Q0275,chrmt,79213,80022,+,gene,Subunit III of cytochrome c oxidase (Complex IV)
6914,tM(CAU)Q2,chrmt,85035,85112,+,tRNA_gene,Mitochondrial formylated methionine tRNA (tRNA...
6915,Q0297,chrmt,85554,85709,+,gene,Dubious open reading frame

In [28]:
m.group(2)

';'